[project]
name = "agent-center"
version = "0.1.0"
description = "AI智能体智能中台"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.141.1",
    "openai>=3.3.1",
    "pydantic-settings>=2.15.0",
    "uvicorn>=0.52.4",
]

[[tool.uv.index]]
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
default = true
